# === Standard MQTT Listener ===
listener 1883 0.0.0.0
allow_anonymous false

# === Global Settings ===
log_dest stderr
max_keepalive 60

# === Secure MQTT Listener ===
listener 8883
protocol mqtt

# ... other TLS settings ...
tls_version tlsv1.2

cafile /mosquitto/config/ca.crt
certfile /mosquitto/config/broker.crt
keyfile /mosquitto/config/broker.key


# Certificate-Based Auth 
require_certificate true
use_identity_as_username true

# TLS 1.2 Cipher Suite 
ciphers ECDHE-RSA-CHACHA20-POLY1305

